### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by ShoiraTa** [newhorizon-tech/space-travelers#25]
We are 2 people in team,
- Link to project - https://github.com/newhorizon-tech/space-travelers/projects/1

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @ShoiraTa and @newhorizon-tech,

Your Kanban board is set up, hence your project is complete!
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
